name: 'Release Asset'
description: 'Upload files to a release'
inputs:
  assert_files:
    description: Glob pattern of files to upload
    required: true
  upload_url:
    description: 'The URL for uploading assets to the release'
    required: true
outputs:
runs:
  using: 'node12'
  main: 'main.js'
